routes/web.php
<?php

use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\HolidayController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PositionController;
use App\Http\Controllers\PresenceController;
use Illuminate\Support\Facades\Route;
use SebastianBergmann\CodeCoverage\Report\Html\Dashboard;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['throttle:global'])->group(function () {

Route::middleware('auth')->group(function () {
    Route::middleware('role:admin,operator,pimpinan')->group(function () {
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
        // positions
        Route::resource('/positions', PositionController::class)->only(['index', 'create']);
        Route::get('/positions/edit', [PositionController::class, 'edit'])->name('positions.edit');
        // employees
        Route::resource('/employees', EmployeeController::class)->only(['index', 'create']);
        Route::get('/employees/edit', [EmployeeController::class, 'edit'])->name('employees.edit');
        Route::post('/employees/importkaryawan', [EmployeeController::class, 'importKaryawan'])->name('employees.import');
        // holidays (hari libur)
        Route::resource('/holidays', HolidayController::class)->only(['index', 'create']);
        Route::get('/holidays/edit', [HolidayController::class, 'edit'])->name('holidays.edit');
        Route::post('/holidays/importholiday', [HolidayController::class, 'importHoliday'])->name('holidays.import');
        // attendances (absensi)
        Route::resource('/attendances', AttendanceController::class)->only(['index', 'create']);
        Route::get('/attendances/edit', [AttendanceController::class, 'edit'])->name('attendances.edit');

        // presences (kehadiran)
        // Route::get('/laporanabsen/laporan', 'App\Http\Controllers\PresenceController@exportExcel');
        Route::get('/laporanabsen/laporan/toexcel', 'App\Http\Controllers\PresenceController@export_excel')->name('laporan.cetakexcel') ;
        Route::get('/laporanabsen/laporan', 'App\Http\Controllers\PresenceController@cetakAbsens')->name('laporan.cetaklapabsen');
        Route::get('/laporanabsen/laporan/excel', 'App\Http\Controllers\PresenceController@cetakAbsensExcel')->name('laporan.cetaklapabsenexcel');
        Route::get('/laporanabsen/laporan/cetak/{tglawal}/{tglakhir}', 'App\Http\Controllers\PresenceController@cetakAbsen')->name('laporan.cetaklaporabsen');
        Route::resource('/presences', PresenceController::class)->only(['index']);
        Route::get('/presences/qrcode', [PresenceController::class, 'showQrcode'])->name('presences.qrcode');
        Route::get('/presences/qrcode/download-pdf', [PresenceController::class, 'downloadQrCodePDF'])->name('presences.qrcode.download-pdf');
        Route::get('/presences/{attendance}', [PresenceController::class, 'show'])->name('presences.show');
        // not present data
        Route::get('/presences/{attendance}/not-present', [PresenceController::class, 'notPresent'])->name('presences.not-present');
        Route::post('/presences/{attendance}/not-present', [PresenceController::class, 'notPresent']);
        // present (url untuk menambahkan/mengubah user yang tidak hadir menjadi hadir)
        Route::post('/presences/{attendance}/present', [PresenceController::class, 'presentUser'])->name('presences.present');
        // Route::post('/presences/{attendance}/acceptPermission', [PresenceController::class, 'acceptPermission'])->name('presences.acceptPermission');
        Route::post('/presences/{attendance}/acceptPermission', 'App\Http\Controllers\PresenceController@acceptPermission')->name('presences.acceptPermission');



        // employees permissions

        Route::get('/presences/{attendance}/permissions', [PresenceController::class, 'permissions'])->name('presences.permissions');
    });

    Route::middleware('role:user,operator,admin,pimpinan')->name('home.')->group(function () {
        Route::get('/', [HomeController::class, 'index'])->name('index');
        // desctination after scan qrcode
        Route::post('/absensi/qrcode', [HomeController::class, 'sendEnterPresenceUsingQRCode'])->name('sendEnterPresenceUsingQRCode');
        Route::post('/absensi/qrcode/out', [HomeController::class, 'sendOutPresenceUsingQRCode'])->name('sendOutPresenceUsingQRCode');

        Route::get('/absensi/{attendance}', [HomeController::class, 'show'])->name('show');
        Route::get('/absensi/{attendance}/permission', [HomeController::class, 'permission'])->name('permission');

    });



    //profile
    Route::resource("/profile", "App\Http\Controllers\ProfileController");

    Route::delete('/logout', [AuthController::class, 'logout'])->name('auth.logout');
});

Route::middleware('guest')->group(function () {
    // auth
    Route::get('/login', [AuthController::class, 'index'])->name('auth.login');
    Route::post('/login', [AuthController::class, 'authenticate']);
});

// Route::get('/ip', function() {
//     $checkLocation=geoip()->getLocation($_SERVER['REMOTE_ADDR']);
//     return $checkLocation->toArray();
//     dd($checkLocation);
// });
});

app/Http/Livewire/AttendanceAbstract.php
<?php

namespace App\Http\Livewire;

use App\Models\Position;
use Livewire\Component;

class AttendanceAbstract extends Component
{
    public $attendance;
    public $positions;
    public $position_ids = [];

    protected $rules = [
        'attendance.title' => 'required|string|min:6',
        'attendance.description' => 'required|string|max:500',
        'attendance.start_time' => 'required|date_format:H:i',
        'attendance.batas_start_time' => 'required|date_format:H:i|after:start_time',
        'attendance.end_time' => 'required|date_format:H:i',
        'attendance.batas_end_time' => 'required|date_format:H:i|after:end_time',
        'attendance.tanggal_awal' => 'required',
        'attendance.tanggal_akhir' => 'required',
        'attendance.code' => 'sometimes|nullable|boolean',
        'position_ids' => 'required|array',
        "position_ids.*"  => "required|distinct|string",
    ];

    public function mount()
    {

        $this->positions = Position::query()->select(['id', 'name'])->get();
    }
}

app/Http/Livewire/AttendanceCreateForm.php
<?php

namespace App\Http\Livewire;

use App\Models\Attendance;
use \Illuminate\Support\Str;

class AttendanceCreateForm extends AttendanceAbstract
{
    public function save()
    {
        // filter value before validate
        $this->position_ids = array_filter($this->position_ids, function ($id) {
            return is_string($id);
        });

        $position_ids = array_values($this->position_ids);

        $this->validate();

        if (array_key_exists("code", $this->attendance) && $this->attendance['code']) // jika menggunakan qrcode
            $this->attendance['code'] = Str::random();

        $attendance = Attendance::create($this->attendance);
        $attendance->positions()->attach($position_ids);

        redirect()->route('attendances.index')->with('success', "Data absensi berhasil ditambahkan.");
    }

    public function render()
    {
        return view('livewire.attendance-create-form');
    }
}

app/Http/Livewire/AttendanceEditForm.php
<?php

namespace App\Http\Livewire;

use App\Models\Attendance;
use Illuminate\Support\Str;

class AttendanceEditForm extends AttendanceAbstract
{
    public $initialCode;

    public function mount()
    {
        parent::mount();
        // format time
        $this->attendance['start_time'] = substr($this->attendance['start_time'], 0, -3);
        $this->attendance['batas_start_time'] = substr($this->attendance['batas_start_time'], 0, -3);
        $this->attendance['end_time'] = substr($this->attendance['end_time'], 0, -3);
        $this->attendance['batas_end_time'] = substr($this->attendance['batas_end_time'], 0, -3);

        $this->attendance['tanggal_awal'] = $this->attendance['tanggal_awal'];
        $this->attendance['tanggal_akhir'] = $this->attendance['tanggal_akhir'];

        $this->initialCode = $this->attendance['code']; // ini untuk pengecekan/mengatasi update code
        $this->attendance['code'] = $this->initialCode ? true : false; // untuk kondisi apakah input code checked

        $this->position_ids = $this->attendance->positions()->pluck('positions.id', 'positions.id')->toArray();
    }

    public function save()
    {
        // filter value before validate (ambil yang hanya checked)
        $this->position_ids = array_filter($this->position_ids, function ($id) {
            return is_string($id);
        });
        $position_ids = array_values($this->position_ids);

        $this->validate();

        $attendance = [];
        if (!$this->attendance->code) {
            $this->attendance->code = null;
            $attendance = $this->attendance->toArray();
        } else {
            $attendance = $this->attendance->toArray();
            // generate code baru jika sebelumnya attendance menggunakan button (atau diubah)
            if (!$this->initialCode) {
                $attendance['code'] = Str::random();
            } else {
                $attendance['code'] = $this->initialCode;
            }
        }

        $this->attendance->update($attendance);
        $this->attendance->positions()->sync($position_ids);

        redirect()->route('attendances.index')->with('success', "Data absensi berhasil diubah.");
    }

    public function render()
    {
        return view('livewire.attendance-edit-form');
    }
}

app/Http/Livewire/EmployeeCreateForm.php
<?php

namespace App\Http\Livewire;

use App\Models\Position;
use App\Models\Role;
use App\Models\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Facades\Hash;
use Livewire\Component;

class EmployeeCreateForm extends Component
{
    public $employees;
    public Collection $roles;
    public Collection $positions;

    public function mount()
    {
        $this->positions = Position::all();
        $this->roles = Role::all();
        $this->employees = [
            ['name' => '', 'email' => '', 'phone' => '', 'password' => '', 'role_id' => User::USER_ROLE_ID, 'position_id' => $this->positions->first()->id]
        ];
    }

    public function addEmployeeInput(): void
    {
        $this->employees[] = ['name' => '', 'email' => '', 'phone' => '', 'password' => '', 'role_id' => User::USER_ROLE_ID, 'position_id' => $this->positions->first()->id];
    }

    public function removeEmployeeInput(int $index): void
    {
        unset($this->employees[$index]);
        $this->employees = array_values($this->employees);
    }

    public function saveEmployees()
    {
        // cara lebih cepat, dan kemungkinan data role tidak akan diubah/ditambah
        $roleIdRuleIn = join(',', $this->roles->pluck('id')->toArray());
        $positionIdRuleIn = join(',', $this->positions->pluck('id')->toArray());
        // $roleIdRuleIn = join(',', Role::all()->pluck('id')->toArray());

        // setidaknya input pertama yang hanya required,
        // karena nanti akan difilter apakah input kedua dan input selanjutnya apakah berisi
        $this->validate([
            'employees.*.name' => 'required',
            'employees.*.email' => 'required|email|unique:users,email',
            'employees.*.phone' => 'required|unique:users,phone',
            'employees.*.password' => '',
            'employees.*.role_id' => 'required|in:' . $roleIdRuleIn,
            'employees.*.position_id' => 'required|in:' . $positionIdRuleIn,
        ]);
        // cek apakah no. telp yang diinput unique
        $phoneNumbers = array_map(function ($employee) {
            return trim($employee['phone']);
        }, $this->employees);
        $uniquePhoneNumbers = array_unique($phoneNumbers);

        if (count($phoneNumbers) != count($uniquePhoneNumbers)) {
            // layar browser ke paling atas agar user melihat alert error
            $this->dispatchBrowserEvent('livewire-scroll', ['top' => 0]);
            return session()->flash('failed', 'Pastikan input No. Telp tidak mangandung nilai yang sama.');
        }

        // alasan menggunakan create alih2 mengunakan ::insert adalah karena tidak looping untuk menambahkan created_at dan updated_at
        $affected = 0;
        foreach ($this->employees as $employee) {
            if (trim($employee['password']) === '') $employee['password'] = '123';
            $employee['password'] = Hash::make($employee['password']);
            User::create($employee);
            $affected++;
        }

        redirect()->route('employees.index')->with('success', "Ada ($affected) data karyawaan yang berhasil ditambahkan.");
    }

    public function render()
    {
        return view('livewire.employee-create-form');
    }
}

app/Http/Livewire/EmployeeEditForm.php
<?php

namespace App\Http\Livewire;

use App\Http\Traits\useUniqueValidation;
use App\Models\Position;
use App\Models\Role;
use App\Models\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Validation\Rule;
use Livewire\Component;

class EmployeeEditForm extends Component
{
    use useUniqueValidation;

    public $employees;
    public Collection $roles;
    public Collection $positions;

    public function mount(Collection $employees)
    {
        $this->employees = []; // reset, karena ada data employees sebelumnya

        foreach ($employees as $employee) {
            $this->employees[] = [
                'id' => $employee->id,
                'name' => $employee->name,
                'email' => $employee->email,
                'original_email' => $employee->email, // untuk cek validasi unique
                'phone' => $employee->phone,
                'original_phone' => $employee->phone, // untuk cek validasi unique nanti
                'role_id' => $employee->role_id,
                'position_id' => $employee->position_id
            ];
        }
        $this->roles = Role::all();
        $this->positions = Position::all();
    }
    public function saveEmployees()
    {
        $roleIdRuleIn = join(',', $this->roles->pluck('id')->toArray());
        $positionIdRuleIn = join(',', $this->positions->pluck('id')->toArray());

        $this->validate([
            'employees.*.name' => 'required',
            'employees.*.email' => 'required|email',
            'employees.*.phone' => 'required',
            'employees.*.password' => '',
            'employees.*.role_id' => 'required|in:' . $roleIdRuleIn,
            'employees.*.position_id' => 'required|in:' . $positionIdRuleIn,
        ]);

        if (!$this->isUniqueOnLocal('phone', $this->employees)) {
            $this->dispatchBrowserEvent('livewire-scroll', ['top' => 0]);
            return session()->flash('failed', 'Pastikan input No. Telp tidak mangandung nilai yang sama dengan input lainnya.');
        }

        if (!$this->isUniqueOnLocal('email', $this->employees)) {
            $this->dispatchBrowserEvent('livewire-scroll', ['top' => 0]);
            return session()->flash('failed', 'Pastikan input Email tidak mangandung nilai yang sama dengan input lainnya.');
        }

        // alasan menggunakan create alih2 mengunakan ::insert adalah karena tidak looping untuk menambahkan created_at dan updated_at
        $affected = 0;
        foreach ($this->employees as $employee) {
            // cek unique validasi
            $employeeBeforeUpdated = User::find($employee['id']);

            if (!$this->isUniqueOnDatabase($employeeBeforeUpdated, $employee, 'phone', User::class)) {
                $this->dispatchBrowserEvent('livewire-scroll', ['top' => 0]);
                return session()->flash('failed', "No. Telp dari data karyawaan {$employee['id']} sudah terdaftar. Silahkan masukan email yang berbeda!");
            }

            if (!$this->isUniqueOnDatabase($employeeBeforeUpdated, $employee, 'email', User::class)) {
                $this->dispatchBrowserEvent('livewire-scroll', ['top' => 0]);
                return session()->flash('failed', "Email dari data karyawaan {$employee['id']} sudah terdaftar. Silahkan masukan email yang berbeda!");
            }

            $affected += $employeeBeforeUpdated->update([
                'name' => $employee['name'],
                'email' => $employee['email'],
                // 'password' => $employee['password'],
                'phone' => $employee['phone'],
                'role_id' => $employee['role_id'],
                'position_id' => $employee['position_id'],
            ]);
        }

        $message = $affected === 0 ?
            "Tidak ada data karyawaan yang diubah." :
            "Ada $affected data karyawaan yang berhasil diedit.";

        return redirect()->route('employees.index')->with('success', $message);
    }

    public function render()
    {
        return view('livewire.employee-edit-form');
    }
}

resources/views/livewire/attendance-create-form.blade.php
<div>
    <form wire:submit.prevent="save" method="post" novalidate>
        @include('partials.alerts')
        <div class="w-100">
            <div class="mb-3">
                <x-form-label id="title" label='Nama/Judul Absensi' />
                <x-form-input id="title" name="title" wire:model.defer="attendance.title" />
                <x-form-error key="attendance.title" />
            </div>
            <div class="mb-3">
                <x-form-label id="description" label='Keterangan' />
                <textarea id="description" name="description" class="form-control"
                    wire:model.defer="attendance.description"></textarea>
                <x-form-error key="attendance.description" />
            </div>
            <div class="mb-3">
                <div class="row">
                    <div class="col-md-6">
                        <x-form-label id="start_time" label='Waktu Absen Masuk' />
                        <x-form-input type="text" maxlength="5" id="start_time" name="start_time"
                            wire:model.defer="attendance.start_time" placeholder="07:00" />
                        <x-form-error key="attendance.start_time" />
                    </div>
                    <div class="col-md-6">
                        <x-form-label id="batas_start_time" label='Batas Waktu Absen Masuk' />
                        <x-form-input type="text" maxlength="5" id="batas_start_time" name="batas_start_time"
                            wire:model.defer="attendance.batas_start_time" />
                        <x-form-error key="attendance.batas_start_time" />
                    </div>
                </div>
                <small class="text-muted d-block mt-1">Masukan dengan format 24:00.</small>
            </div>
            <div class="mb-3">
                <div class="row">
                    <div class="col-md-6">
                        <x-form-label id="end_time" label='Waktu Absen Pulang' />
                        <x-form-input type="text" maxlength="5" id="end_time" name="end_time"
                            wire:model.defer="attendance.end_time" placeholder="15:00" />
                        <x-form-error key="attendance.end_time" />
                    </div>
                    <div class="col-md-6">
                        <x-form-label id="batas_end_time" label='Batas Waktu Absen Pulang' />
                        <x-form-input type="text" maxlength="5" id="batas_end_time" name="batas_end_time"
                            wire:model.defer="attendance.batas_end_time" />
                        <x-form-error key="attendance.batas_end_time" />
                    </div>
                </div>
                <small class="text-muted d-block mt-1">Masukan dengan format 24:00.</small>
            </div>

            {{-- Tanggal Range --}}
            <div class="mb-3">
                <div class="row">
                    <div class="col-md-6">
                        <x-form-label id="tanggal_awal" label='Tanggal Awal Absen' />
                        <x-form-input type="date" id="tanggal_awal" name="tanggal_awal"
                            wire:model.defer="attendance.tanggal_awal" placeholder="15:00" />
                        <x-form-error key="attendance.tanggal_awal" />
                    </div>
                    <div class="col-md-6">
                        <x-form-label id="tanggal_akhir" label='Tanggal Akhir Absen' />
                        <x-form-input type="date" id="tanggal_akhir" name="tanggal_akhir"
                            wire:model.defer="attendance.tanggal_akhir" />
                        <x-form-error key="attendance.tanggal_akhir" />
                    </div>
                </div>
                <small class="text-muted d-block mt-1">Masukan Tanggal.</small>
            </div>

            <div class="mb-3">
                <x-form-label id="positions" label='Posisi Karyawaan' />
                <div class="row ms-1">
                    @foreach ($positions as $position)
                    <div class="form-check col-sm-4">
                        <input class="form-check-input" type="checkbox" value="{{ $position->id }}"
                            wire:model.defer="position_ids.{{ $position->id }}"
                            id="flexCheckPosition{{ $loop->index }}">
                        <label class="form-check-label" for="flexCheckPosition{{ $loop->index }}">
                            {{ $position->name }}
                        </label>
                    </div>
                    @endforeach
                </div>
                <small class="text-muted d-block mt-1">Pilih posisi karyawaan yang akan menggunakan absensi ini.</small>
                <x-form-error key="position_ids" />
                {{-- tom-select init script ada di create.blade.php attendances --}}
            </div>


            {{-- <div class="mb-3">
                <x-form-label id="flexCheckCode" label='Ingin Menggunakan QRCode (default menggunakan tombol)' />
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" wire:model.defer="attendance.code"
                        id="flexCheckCode">
                    <label class="form-check-label" for="flexCheckCode">
                        Menggunakan QRCode
                    </label>
                    <x-form-error key="attendance.code" />
                </div>
            </div> --}}

        </div>

        <div class="d-flex justify-content-between align-items-center mb-5">
            <button class="btn btn-primary">
                Simpan
            </button>
        </div>
    </form>
</div>

resources/views/livewire/presence-form.blade.php
<div>
    {{-- get lokasi input --}}
    <div  style="display: none;">
        <input type="text" wire:model="lokasi" id="lokasi" name="lokasi">
        <input type="text" wire:model="if_outside_radius" id="if_outside_radius" name="if_outside_radius">
    </div>



{{-- {{ $lokasi }} --}}


    @if ($holiday)
    <div class="alert alert-success">
        <small class="fw-bold">Hari ini adalah hari libur.</small>
    </div>
    @elseif($weekend)
    <div class="alert alert-success">
        <small class="fw-bold">Hari ini adalah hari libur.</small>
    </div>
    @else

        {{-- jika absen pulang sudah dimulai, dan karyawan belum absen masuk dan belum absen pulang --}}
        @if ($attendance->data->is_end && !$data['is_has_enter_today'] && $attendance->data->in_date_range)
        <button class="btn btn-primary px-3 py-2 btn-sm fw-bold d-block w-100" wire:click="sendLateEnterPresence"
            wire:loading.attr="disabled" wire:target="sendLateEnterPresence">Absen Masuk & Pulang Sekaligus (Hanya yang lupa absen masuk!!!)</button>
            <br>
            <textarea class="px-3 pt-2 pb-5 rounded fw-normal block w-100" style="resize: none;" cols="100" placeholder="CATATAN (opsional)" id="catatan" name="catatan" wire:model="catatan"></textarea>
        @endif
<br>


    {{-- jika tidak menggunakan qrcode (button) dan karyawan saat ini tidak menekan tombol izin --}}
    @if (!$attendance->data->is_using_qrcode && !$data['is_there_permission'] && $attendance->data->in_date_range)

    {{-- jika belum absen dan absen masuk sudah dimulai --}}
    @if ($attendance->data->is_start && !$data['is_has_enter_today'] && $attendance->data->in_date_range)
    <button class="btn btn-primary px-3 py-2 btn-sm fw-bold d-block w-100 mb-2" wire:click="sendEnterPresence"
        wire:loading.attr="disabled" wire:target="sendEnterPresence">Masuk</button>
        <textarea class="px-3 pt-2 pb-5 rounded fw-normal block w-100" style="resize: none;" cols="100" placeholder="CATATAN (opsional)" id="catatan" name="catatan" wire:model="catatan"></textarea>
        <br>
    <a href="{{ route('home.permission', $attendance->id) }}"
        class="btn btn-info px-3 py-2 btn-sm fw-bold d-block w-100">Izin</a>
    @endif

    @if ($data['is_has_enter_today'] && $attendance->data->in_date_range)
    <div class="alert alert-success">
        <small class="d-block fw-bold text-success">Anda sudah berhasil mengirim absensi masuk.</small>
    </div>
    @endif

    {{-- jika absen pulang sudah dimulai, dan karyawan sudah absen masuk dan belum absen pulang --}}
    @if ($attendance->data->is_end && $data['is_has_enter_today'] && $data['is_not_out_yet'] && $attendance->data->in_date_range)
    <button class="btn btn-primary px-3 py-2 btn-sm fw-bold d-block w-100" wire:click="sendOutPresence"
        wire:loading.attr="disabled" wire:target="sendOutPresence">Pulang</button>
        <br>
    <textarea class="px-3 pt-2 pb-5 rounded fw-normal block w-100" style="resize: none;" cols="100" placeholder="CATATAN (opsional)" id="catatan" name="catatan" wire:model="catatan"></textarea>
    @endif

    {{-- sudah absen masuk dan absen pulang --}}
    @if ($data['is_has_enter_today'] && !$data['is_not_out_yet'] && $attendance->data->in_date_range)
    <div class="alert alert-success">
        <small class="d-block fw-bold text-success">Anda sudah melakukan absen masuk dan absen pulang.</small>
    </div>
    @endif

    {{-- jika sudah absen masuk dan belum saatnya absen pulang --}}
    @if ($data['is_has_enter_today'] && !$attendance->data->is_end && $attendance->data->in_date_range)
    <div class="alert alert-danger">
        <small class="fw-bold">Belum saatnya melakukan absensi pulang.</small>
    </div>
    @endif
    @endif

    @if($data['is_there_permission'] && !$data['is_permission_accepted'] && $attendance->data->in_date_range)
    <div class="alert alert-info">
        <small class="fw-bold">Permintaan izin sedang diproses (atau masih belum di terima).</small>
    </div>
    @endif

    @if($data['is_there_permission'] && $data['is_permission_accepted'] && $attendance->data->in_date_range)
    <div class="alert alert-success">
        <small class="fw-bold">Permintaan izin sudah diterima.</small>
    </div>
    @endif

    @endif

</div>
@push('script')
<script>

    // script lokasi
const lokasi = document.getElementById('lokasi');
const tottest = document.getElementById('tottest');
if(navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(successCallback, errorCallback)
}

function successCallback(position){
    document.addEventListener('livewire:load',function ()
        {
            @this.lokasi = position.coords.latitude + "," + position.coords.longitude;
        });
    //lokasi.value = position.coords.latitude + "," + position.coords.longitude;
    var map = L.map('map').setView([position.coords.latitude, position.coords.longitude], 17);
    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 19,
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
}).addTo(map);

var marker = L.marker([position.coords.latitude, position.coords.longitude]).addTo(map);

marker.bindPopup("Lokasi Saya").openPopup();

// Define the circle
const circleCenter = L.latLng(-2.5539087728895846, 140.48924550067477); // Replace with your circle center coordinates
// const circleCenter = L.latLng(-2.554243144398407, 140.48968581695647); // FIX coord
const circleRadius = 170; // Replace with your circle radius in meters
const circle = L.circle(circleCenter, {
  radius: circleRadius,
}).addTo(map);

// Define the point
const point = L.latLng(position.coords.latitude, position.coords.longitude); // Replace with your point coordinates

// Check if the point is outside the circle
const distanceToCenter = point.distanceTo(circleCenter);
if (distanceToCenter > circleRadius) {
    swal("PERHATIAN!", "Lokasi Anda Sekarang Masih diluar Radius Kampus!", "error");
    document.addEventListener('livewire:load',function ()
        {
            @this.if_outside_radius = "Diluar Radius";
        });
} else {
    swal("PERHATIAN!", "Lokasi Dalam Radius Kampus, Silahkan Lakukan Absensi!", "success");
    document.addEventListener('livewire:load',function ()
        {
            @this.if_outside_radius = "Didalam Radius";
        });
}
}

function errorCallback() {

}
</script>
@endpush